export const ADD_PERSON_TO_FAVORITE = "ADD_PERSON_TO_FAVORITE";
export const REMOVE_PERSON_FROM_FAVORITE = "REMOVE_PERSON_FROM_FAVORITE";

export const THEME_LIGHT = "light";
export const THEME_DARK = "dark";
export const THEME_ROBO = "robo";

export const CHANGE_THEME = "CHANGE_THEME";

export const SAVE_SEARCH_RESULTS = "SAVE_SEARCH_RESULTS";

export const FETCH_ALL_PEOPLE = "FETCH_ALL_PEOPLE";
export const SAVE_CHECKED_FILTERS = "SAVE_CHECKED_FILTERS";
